In [1]:
import pandas as pd

survey_results_df = pd.read_csv('/content/drive/MyDrive/проект 2/survey_results_public.csv')
display(survey_results_df.head())

/tmp/ipython-input-3424077779.py:3: DtypeWarning: Columns (56,74,92,97,98,105,109,110,132,162,165) have mixed types. Specify dtype option on import or set low_memory=False.
  survey_results_df = pd.read_csv('/content/drive/MyDrive/проект 2/survey_results_public.csv')

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [2]:
survey_schema_df = pd.read_csv('/content/drive/MyDrive/проект 2/survey_results_schema.csv')
display(survey_schema_df.head())

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0

# Завдання 1. Підрахунок загальної кількості респондентів

In [4]:
# Загальна кількість респондентів = кількість рядків
total_respondents = survey_results_df.shape[0]
total_respondents

49191

# Завдання 2. Аналіз повноти відповідей респондентів

In [6]:
# 1. Отримуємо список питань з файлу survey_results_schema (поле qname)
question_names = set(survey_schema_df['qname'].dropna())

# 2. Інтерсекція: які з цих питань реально є в колонках основної таблиці
available_questions = list(question_names.intersection(survey_results_df.columns))

# 3. Фільтруємо тільки ці колонки і дропаємо рядки з пропусками
complete_rows = survey_results_df[available_questions].dropna()

# 4. Кількість респондентів, які відповіли на всі ці питання
complete_respondents = complete_rows.shape[0]
complete_respondents

0

# Завдання 3. Статистичний аналіз досвіду респондентів

In [8]:
workexp = pd.to_numeric(survey_results_df['WorkExp'], errors='coerce')

mean_workexp = workexp.mean()
median_workexp = workexp.median()
mode_workexp = workexp.mode().iloc[0]

pd.Series({
    'mean': mean_workexp,
    'median': median_workexp,
    'mode': mode_workexp
})

mean      13.367403
median    10.000000
mode      10.000000
dtype: float64

# Завдання 4. Аналіз віддаленої роботи

In [11]:
# 1.
[col for col in survey_results_df.columns if 'remote' in col.lower()]

# 2. Створюємо булеву маску: чи містить рядок слово "Remote"
remote_mask = survey_results_df['RemoteWork'].fillna('').str.contains('Remote', case=False)

# 3. Кількість респондентів, які працюють віддалено
remote_count = remote_mask.sum()
remote_count

np.int64(17663)

# Завдання 5. Визначення популярності Python

In [13]:
# Знайдемо колонку з мовами програмування
[col for col in survey_results_df.columns if 'language' in col.lower()]

languages_col = 'LanguageHaveWorkedWith'  # змінити, якщо у тебе інша назва

# Булева маска: чи містить рядок 'Python'
python_mask = survey_results_df[languages_col].fillna('').str.contains('Python')

# Відсоток респондентів, які програмують на Python
python_percent = python_mask.mean() * 100
python_percent

np.float64(37.53938728629221)

# Завдання 6. Аналіз шляхів навчання програмуванню

In [15]:
[col for col in survey_results_df.columns if 'learn' in col.lower()]

learn_col = 'LearnCode'  # змінити, якщо назва інша

online_mask = survey_results_df[learn_col].str.contains('Online course', case=False, na=False)

online_learners_count = survey_results_df[online_mask].shape[0]
online_learners_count

21212

# Завдання 7. Географічний аналіз компенсації Python-розробників

In [19]:
# 1. Фільтруємо лише Python-розробників
python_devs = survey_results_df[ survey_results_df[languages_col].fillna('').str.contains('Python') ].copy()

# 2. Переконуємось, що компенсація — числова
python_devs['ConvertedCompYearly'] = pd.to_numeric(
    python_devs['ConvertedCompYearly'], errors='coerce'
)

# 3. Групування по країні: середня та медіанна компенсація
python_comp_by_country = python_devs.groupby('Country')['ConvertedCompYearly'].agg(
    mean_comp='mean',
    median_comp='median'
).reset_index()

python_comp_by_country.head()

       Country      mean_comp  median_comp
0  Afghanistan   22328.666667       1000.0
1      Albania   47217.600000      50000.0
2      Algeria   20187.285714       7088.0
3      Andorra  226103.500000     226103.5
4       Angola            NaN          NaN

# Завдання 8. Аналіз освіти найбільш оплачуваних спеціалістів

In [20]:
[col for col in survey_results_df.columns if 'comp' in col.lower()]

top5 = survey_results_df.nlargest(5, 'ConvertedCompYearly')[
    ['ConvertedCompYearly', 'EdLevel', 'Country']
]

top5

,ConvertedCompYearly,EdLevel,Country
34267,50000000.0,"Associate degree (A.A., A.S., etc.)",United States of America
28700,33552715.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Ukraine
43143,18387548.0,"Associate degree (A.A., A.S., etc.)",Poland
35353,15430267.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Iran, Islamic Republic of..."
45971,13921760.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Netherlands